---
title: "do_plots"
author: "Xiao Chen"
date: "2024-12-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All the codes used to do plots for the rumination network project

Please first replace the work_dir with your own path

## Initialization

```{r initialization}

rm(list = ls())
cat("\014")

library(ggplot2)
library(dplyr)
library(corrplot)
library(readr)
library(rio)
library(robust)
library(igraph)
library(ggraph)
library(tidygraph)
library(RColorBrewer)
library(scales)  # For rescaling values
library(fsbrain)
library(gifti)
library(freesurferformats)
library(rgl)
library(circlize)
library(readxl) 
library(reshape2)

work_dir = "xxxx"
data_dir <- paste(work_dir, "/data", sep = "")
output_dir <- paste(work_dir, "/outputs", sep = "")
```

## "Gephi like" network graphs (Figure 1)

```{r}
file_name <- "dis_mdd"
# file_name <- "rum_mdd"
connection_matrix <- as.matrix(read.csv(paste(data_dir, "/", file_name, "_oneT.csv", sep = ""), header = FALSE))
connection_matrix[abs(connection_matrix) < 7.24] <- 0 #Bonferoni correction: p < 0.001/73536

g <- graph_from_adjacency_matrix(connection_matrix, mode = "undirected", weighted = TRUE, diag = FALSE)
# Mark negative edges explicitly
E(g)$negative <- E(g)$weight < 0
E(g)$abs_weight <- abs(E(g)$weight)

network_membership <- read.csv(paste(data_dir, "/node_info.csv", sep = ""), header = TRUE)$network
network_colors <- c(
  rgb(120, 18, 134, maxColorValue = 255),   
  rgb(70, 130, 180, maxColorValue = 255),  
  rgb(0, 118, 14, maxColorValue = 255),   
  rgb(196, 58, 250, maxColorValue = 255), 
  rgb(220, 248, 164, maxColorValue = 255), 
  rgb(230, 148, 34, maxColorValue = 255),  
  rgb(242, 237, 47, maxColorValue = 255), 
  rgb(40, 46, 144, maxColorValue = 255),
  rgb(106, 188, 67, maxColorValue = 255)
)
network_names <- c("Visual", "Somatomotor", "Dorsal attention", "Ventral attention", "Limbic", "Frontoparietal", "Default core", "Default DMPFC", "Default MTL")
network_labels <- factor(network_membership, levels = 1:9, labels = network_names)

# the significant node from the mixed effect analysis of graph theory
highlight_node <- 301
tg <- as_tbl_graph(g) %>%
  mutate(network = network_labels)

# Assume your graph 'g' and weights already created
set.seed(123)
# Stronger correlations get higher attraction (use abs_weight)
custom_layout <- create_layout(
  tg, 
  layout = "fr", 
  weights = abs(E(g)$weight)*3,
  niter = 3000,        # more iterations for better convergence
  area = vcount(g)^3,  # Increase area to separate unrelated nodes further
  repulserad = vcount(g)^3  # Further increase repulsion between unrelated nodes
)

highlight_node <- "V301"

# Plotting
ggraph(custom_layout) +
  geom_edge_link(aes(edge_alpha = abs_weight,
                     edge_color = negative,
                     edge_width = abs_weight,
                     linetype = negative)) +
  scale_edge_color_manual(name = "Edge type",
                          values = c(`FALSE` = "gray60", `TRUE` = "red"),
                          labels = c("Positive", "Negative")) +
  scale_edge_alpha(range = c(0.3, 1), guide = "none") +
  scale_edge_width(range = c(0.4, 4), guide = "none") +
  scale_edge_linetype_manual(values = c(`FALSE` = "solid", `TRUE` = "dashed"),
                             guide = "none") +
  geom_node_point(aes(color = network, shape = ifelse(name == highlight_node, "2", "1"), size = factor(ifelse(name == highlight_node, "big", "small")))) +
  scale_size_manual(values = c("big" = 12, "small" = 8)) + 
  scale_color_manual(values = network_colors, name = "Network") +
  theme_void() +
  theme(legend.position = "right") +
  guides(edge_color = guide_legend(override.aes = list(edge_width = 2)))

ggsave(paste(output_dir, "/",file_name,"_network_layout.png", sep = ""), 
       width = 25, height = 20, units = "cm", dpi = 300)
```

## To plot the adjusted FCs (Figure 2)

```{r plotting}
# This .csv file list all the edges that survive the FDR correction
stats_info <- read.csv(paste(data_dir, "/MDD_NetworkLevel_stats.csv", sep = ""))

for (i in 1:nrow(stats_info)){
  node1 <- stats_info$node1[i]
  node2 <- stats_info$node2[i]
  FC_MDD <- read.csv(paste(data_dir, "/", node1, "_", node2, "_MDD_NetworkLevel_AdjustedFC.csv", sep = ""), header = FALSE)
  FC_MDD$V2[FC_MDD$V2 == -1] <- 2
  FC_HC <- read.csv(paste(data_dir, "/", node1, "_", node2, "_HC_NetworkLevel_AdjustedFC.csv", sep = ""), header = FALSE)
  FC_HC$V2[FC_HC$V2 == 1] <- 3
  FC_HC$V2[FC_HC$V2 == -1] <- 4
  rio_txt <- rbind(FC_MDD, FC_HC)

  rio_txt$id <- c(rep(1:sum(rio_txt$V2 == 1), 2), rep(1001:(1000 + sum(rio_txt$V2 == 3)), 2))
  rio_txt$V2 <- factor(rio_txt$V2, levels = c(1,2,3,4),labels = c("MDD_Rum", "MDD_Dis", "HC_Rum", "HC_Dis"))
  colnames(rio_txt)[1:2] <- c("Adjusted FC", "Condition")

  ggplot(data = rio_txt, mapping = aes(x = Condition, y = `Adjusted FC`, fill = Condition)) +
  theme_classic(base_size = 38) + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.1, hjust = 1)) +
  geom_violin(show.legend = FALSE) + 
  geom_point(size = 6, alpha = 0.8, show.legend = FALSE) +
  geom_line(group = rio_txt$id, size = 1.6, alpha = 0.8) +
  scale_fill_manual(values = c("#FF2442", "#3DB2FF", "#F9C0AB", "#B1F0F7"))

  ggsave(paste(output_dir, "/", node1, "_", node2, "_Adjusted_FC.png", sep = ""), width = 24, height = 22, units = "cm", dpi = 300)
}
```

## Plotting number count (Figure 3B)

```{r}
# plot positive results
label <- "HC_pos_ratio"
# label <- "MDD_pos_ratio"
data <- read.csv(paste(data_dir,"/", label ,".csv", sep = ""), header = FALSE)
mat <- as.matrix(data)
mat <- floor(mat * 100)
labels <- c('VN','SMN','DAN','VAN','LN','FPN','DMN core','DMN DMPFC','DMN MTL')
rownames(mat) <- colnames(mat) <- labels
df <- melt(mat, na.rm = TRUE)
colnames(df) <- c("Y", "X", "Ratio")

p <- ggplot(df, aes(x = X, y = Y, fill = Ratio)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Ratio), color = "white", size = 5) +
  scale_fill_gradient(low = "#e5e5e5", high = "#BF3131", na.value = "transparent", limits = c(0, 30)) +
  scale_y_discrete(limits = rev(levels(factor(df$Y)))) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_fixed()
p
ggsave(paste(output_dir, "/", label, ".png", sep = ""), plot = p, width = 6, height = 6, dpi = 600)

# plot negative results
label <- "HC_neg_ratio"
# label <- "MDD_neg_ratio"
data <- read.csv(paste(data_dir,"/", label ,".csv", sep = ""), header = FALSE)
mat <- as.matrix(data)
mat <- floor(mat * 100)
labels <- c('VN','SMN','DAN','VAN','LN','FPN','DMN core','DMN DMPFC','DMN MTL')
rownames(mat) <- colnames(mat) <- labels
df <- melt(mat, na.rm = TRUE)
colnames(df) <- c("Y", "X", "Ratio")

p <- ggplot(df, aes(x = X, y = Y, fill = Ratio)) +
  geom_tile(color = "white") +
  geom_text(aes(label = Ratio), color = "white", size = 5) +
  scale_fill_gradient(low = "#e5e5e5", high = "#205781", na.value = "transparent", limits = c(0, 30)) +
  scale_y_discrete(limits = rev(levels(factor(df$Y)))) +
  theme_minimal() +
  theme(axis.title = element_blank(),
        panel.grid = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_fixed()
# 
p
ggsave(paste(output_dir, "/", label, ".png", sep = ""), plot = p, width = 6, height = 6, dpi = 600)
```

## To plot the adjusted GTC (Figure 4)

```{r}
GTC_MDD <- read.csv(paste(data_dir, "/ParMed_4_R_MDD_GTC_adj.csv", sep = ""), header = FALSE)
GTC_MDD$V2[GTC_MDD$V2 == -1] <- 2
GTC_HC <- read.csv(paste(data_dir, "/ParMed_4_R_HC_GTC_adj.csv", sep = ""), header = FALSE)
GTC_HC$V2[GTC_HC$V2 == 1] <- 3
GTC_HC$V2[GTC_HC$V2 == -1] <- 4
rio_txt <- rbind(GTC_MDD, GTC_HC)

rio_txt$id <- c(rep(1:sum(rio_txt$V2 == 1), 2), rep(1001:(1000 + sum(rio_txt$V2 == 3)), 2))
rio_txt$V2 <- factor(rio_txt$V2, levels = c(1,2,3,4),labels = c("MDD_Rum", "MDD_Dis", "HC_Rum", "HC_Dis"))
colnames(rio_txt)[1:2] <- c("Eigenvector Centrality", "Condition")

ggplot(data = rio_txt, mapping = aes(x = Condition, y = `Eigenvector Centrality`, fill = Condition)) +
  theme_classic(base_size = 38) + xlab(NULL) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1.1, hjust = 1)) +
  geom_violin(show.legend = FALSE) + 
  geom_point(size = 6, alpha = 0.8, show.legend = FALSE) +
  geom_line(group = rio_txt$id, size = 1.6, alpha = 0.8) +
  scale_fill_manual(values = c("#FF2442", "#3DB2FF", "#F9C0AB", "#B1F0F7"))

ggsave(paste(output_dir, "/EC_adjusted_v2.png", sep = ""), width = 24, height = 22, units = "cm", dpi = 300)

```

## To plot scatter plots, for GTA metrics (Figure 4)

```{r}
file <- paste(data_dir, "/ParMed_4_R_HAMD_Sum.csv", sep = "")
rio_txt <- import(file) 
colnames(rio_txt)[1:2] <- c("Eigenvector Centrality (delta)", "HAMD Score")

ggplot(data = rio_txt, mapping = aes(x = `Eigenvector Centrality (delta)`, y = `HAMD Score`)) +
        theme_classic(base_size = 30) +
        geom_point(size = 10) + geom_smooth(method = "lm") +
        scale_fill_brewer(palette = "Set1") +
        theme(plot.title = element_text(hjust = 0.5))

ggsave(paste(output_dir, "/GTA_corr_v2.png", sep = ""), 
       width = 25, height = 20, units = "cm", dpi = 300)

# test the robustness of this result
rio_txt <- rio_txt[rio_txt$Delta_degree >= -0.01, ]
y <- rio_txt$HAMD
x <- rio_txt$Delta_degree
test <- cor.test(x, y, method = "pearson")
print(test)
```
